last_update = 1664062083285
api_url = "https://api.playit.cloud/agent"
ping_target_addresses = ["23.133.216.1:5530", "ping.playit.gg"]
control_address = "control.playit.gg"
refresh_from_api = true
api_refresh_rate = 5000
ping_interval = 5000
secret_key = "ec919017fe13b603f3a2e32699e1e8533fb6e04ea7f355124540147d5c86682d"

[[mappings]]
proto = "tcp"
tunnel_ip = "147.185.221.180"
tunnel_from_port = 60277
local_ip = "101.100.136.143"
local_port = 2560
