last_update = 1664084699594
api_url = "https://api.playit.cloud/agent"
ping_target_addresses = ["23.133.216.1:5530", "ping.playit.gg"]
control_address = "control.playit.gg"
refresh_from_api = true
api_refresh_rate = 5000
ping_interval = 5000
secret_key = "demo"

[[mappings]]
proto = "tcp"
tunnel_ip = "demo"
tunnel_from_port = demo
local_ip = "demo"
local_port = demo
